[tool.poetry]
name = "souno-awdtf"
version = "0.1.0"
description = ""
authors = ["souno <souno@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
